version: "2"

services:
   multiroomaudio:
     image: s1lvester/docker-snapcast-multiroomaudio
     environment:
       SPOTIFY_BITRATE: 160
       SPOTIFY_NAME: Snapcast
     networks:
       mylan:
         ipv4_address: 192.168.188.88
     
networks:
  mylan:
    external: true
